markdown: kramdown
highlighter: none
permalink: pretty
encoding: utf-8
port: 4009
main_baseurl: https://bitwarden.com

sass:
  sass_dir: ./_scss
  style: compressed

exclude:
  - node_modules
  - bitwarden-help.sln
  - package.json
  - package-lock.json
  - gulpfile.js
  - appveyor.yml
  - README.md

include:
  - '.nojekyll'

collections:
  categories:
    output: true
    permalink: /:path/
  articles:
    output: true
    permalink: /article/:name/

plugins:
  - jekyll-redirect-from