markdown: kramdown
permalink: pretty
encoding: utf-8
port: 4009

exclude:
  - node_modules
  - bitwarden-help.sln
  - package.json
  - gulpfile.js
  - README.md

collections:
  categories:
    output: true
    permalink: /:path/
  articles:
    output: true
    permalink: /article/:name/
