image:
- Ubuntu1804

branches:
  except:
    - gh-pages

stack: node 10, ruby 2.6.0

init:
- sh: |
    if [ "${DEBUG_SSH}" == "true" ]
    then
      curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
    fi

install:
- gem install jekyll bundler
- sh: |
    if [ "${GH_TOKEN}" != "" ]
    then
      git config --global credential.helper store
      echo "https://${GH_TOKEN}:x-oauth-basic@github.com" >> ~/.git-credentials
      git config --global user.email "ci@bitwarden.com"
      git config --global user.name "Bitwarden CI"
    fi

before_build:
- node --version
- npm --version
- ruby --version
- jekyll --version

build_script:
- npm install
- sh: |
    if [ "${GH_TOKEN}" != "" ]
    then
      npm run deploy
    else
      npm run build
    fi

on_finish:
- sh: |
    if [ "${DEBUG_SSH}" == "true" ]
    then
      export APPVEYOR_SSH_BLOCK=true
      curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
    fi
