name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Set up Jekyll
        run: gem install bundler jekyll jekyll-redirect-from

      - name: Print environment
        run: |
          node --version
          npm --version
          ruby --version
          jekyll --version

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Node dependencies
        run: npm install

      - name: Build site
        if: github.ref != 'refs/heads/master'
        run: npm run build:prod

      - name: Build site for S3
        if: github.ref == 'refs/heads/master'
        run: npm run build:prod:sub

      - name: Deploy to S3
        if: github.ref == 'refs/heads/master'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: '_site'
          DEST_DIR: 'help'
